## NUMPY ##

#### Numpy keep better in the ram and cost least for us.But we have to define the same data type. [int,int,int] or [str,str,str,str]  ####
#### We able to calculate high level numerical operations and vectorial operations. ####

In [3]:
import numpy as np

In [5]:
x=[7,8,9,10]
y=[2,3,4,5]              #x and y are list.

In [13]:
x=np.array([7,8,9,10])         #'array' is the daa type of numpy library
y=np.array([2,3,4,5])

In [41]:
x*y                             

array([14, 24, 36, 50])

In [40]:
a=x*y                           #We save array that create
a

array([14, 24, 36, 50])

In [43]:
a.ndim                         #'ndim' is dimension length of array

1

In [44]:
a.shape             #'shape' is dimension knowledge of array.'4' is amount of element.After ',' is dimension knowledge of array

(4,)

In [45]:
a.size               #'size' give us amount of element.

4

In [46]:
a.dtype                  #'dtype' give us the type of integer.

dtype('int32')

In [48]:
z.ndim

2

In [49]:
z.shape

(4, 5)

In [50]:
z.size 

20

In [51]:
z.dtype

dtype('float64')

In [9]:
type(x)             #'x' is a numpy array

numpy.ndarray

In [10]:
type(y)           #'y is a numpy array

numpy.ndarray

In [12]:
x=np.array([7.58,8,9,10])              # all the them become the same type.
x      

array([ 7.58,  8.  ,  9.  , 10.  ])

In [19]:
x=np.array([7.58,8,9,10], dtype='int')    
x

array([ 7,  8,  9, 10])

In [18]:
x=np.array([7.58,8,9,10], dtype='str')  
x

array(['7.58', '8', '9', '10'], dtype='<U4')

### Array Creation ###

In [20]:
np.zeros(12)                                 #fonk ve döngüler gezmek aralık olşturmak-ızgaralarda gezinmek için.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.ones((25), dtype='str')                               

array(['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
       '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
      dtype='<U1')

#### If we write different number from '0,1 and 2', we use 'full' function. ####

In [27]:
np.full((4,5),5)                         

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [25]:
np.ones((6,2), dtype='int')

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [34]:
np.linspace(5,6, 10)           #'linspace' create ten numbers from 5 to 6 .

array([5.        , 5.11111111, 5.22222222, 5.33333333, 5.44444444,
       5.55555556, 5.66666667, 5.77777778, 5.88888889, 6.        ])

In [35]:
np.arange(1,30, 2)            #'arange' give the range and rise as 'range' function.

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

#### We create array ramdomly with normal distribution.First value(5) is average and second value(4) is standard deviation.(4,5) are the row and column of array. ####
 

In [47]:
z=np.random.normal(5,4, (4,5))
z

array([[ 7.19359222,  6.86660111,  6.47782171,  1.67832029,  3.56062975],
       [ 8.2782432 ,  1.91978393,  0.8836276 ,  8.8567829 ,  4.82732997],
       [ 6.53048698,  0.973569  ,  5.74609943,  3.21694363,  1.23019814],
       [-2.514943  , -0.03662686,  8.49567317,  3.64561933,  8.5315377 ]])

In [38]:
np.random.randint(5,30, (4,5))

array([[20, 13, 18, 15,  9],
       [25, 11, 15, 25,  6],
       [17, 14, 25, 24,  9],
       [ 5,  6, 23, 24,  8]])

### Reshape ###

In [54]:
np.arange(4,15,3)                          

array([ 4,  7, 10, 13])

In [72]:
np.arange(4,16)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [73]:
np.arange(4,16).reshape((4,3))   #We use 'reshape' one more dimension from one or 
                                 #we want to change dimension as the same value we change dimension 

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [103]:
n=np.arange(1,10).reshape((3,3))
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
c=np.arange(1,10)
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
c.ndim

1

In [92]:
ı=c.reshape((1,9))                           
ı

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [93]:
ı.ndim

2

### Concatenate ###

In [97]:
x

array([ 7,  8,  9, 10])

In [98]:
y

array([2, 3, 4, 5])

In [100]:
np.concatenate([x,y])

array([ 7,  8,  9, 10,  2,  3,  4,  5])

In [104]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
np.concatenate([n,n])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
np.concatenate([n,n], axis=0)           # 0=row

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [107]:
np.concatenate([n,n], axis=1)          #1=column

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

#### Split ####

In [108]:
t=np.array([52,45,86,42,120])

In [111]:
np.split(t, (2,4))                             #Split from second element and from fourth element.

[array([52, 45]), array([86, 42]), array([120])]

In [120]:
w,q,r=np.split(t, (2,4))

In [121]:
w

array([52, 45])

In [122]:
q

array([86, 42])

In [123]:
r

array([120])

In [114]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [117]:
np.split(n, (1,2))

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [137]:
d=np.arange(2,22, 2).reshape(5,2)
d

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20]])

In [139]:
np.vsplit(n, [2])

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]])]

In [142]:
on,b=np.vsplit(n, [2])

In [143]:
on

array([[1, 2, 3],
       [4, 5, 6]])

In [144]:
b

array([[7, 8, 9]])

In [145]:
np.hsplit(n, [2])

[array([[1, 2],
        [4, 5],
        [7, 8]]),
 array([[3],
        [6],
        [9]])]

In [146]:
on2,b2=np.hsplit(n, [2])

In [147]:
on2

array([[1, 2],
       [4, 5],
       [7, 8]])

In [148]:
b2

array([[3],
       [6],
       [9]])

#### Sort ####

In [180]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [170]:
z=np.arange(18,0,-1)

In [171]:
np.sort(z)                                                 #np.sort(z) does not change the sorting of the numbers.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [172]:
z

array([18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,
        1])

In [178]:
z.sort()
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [179]:
z                                                        #z.sort() change the sorting of the numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [184]:
np.arange(19,1,-1).reshape(2,9)

array([[19, 18, 17, 16, 15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6,  5,  4,  3,  2]])

In [186]:
k=np.arange(19,1,-1).reshape(2,9)
k

array([[19, 18, 17, 16, 15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6,  5,  4,  3,  2]])

In [188]:
np.sort(k)

array([[11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [190]:
k.sort()
k

array([[11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [191]:
k                                                               #z.sort() change the sorting of the numbers

array([[11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10]])

#### Index ####

In [194]:
k

array([[11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [193]:
k[1]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [198]:
k[-1]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [195]:
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [196]:
z[5]

6

In [197]:
z[2]

3

In [199]:
z[10]

11

In [200]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [201]:
n[0,0]

1

In [202]:
n[1,2]

6

In [203]:
n[0]

array([1, 2, 3])

In [205]:
n[1,2]=888
n                                                            #fixtype

array([[  1,   2,   3],
       [  4,   5, 888],
       [  7,   8,   9]])

#### Slice ####

In [207]:
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [206]:
z[1:5]

array([2, 3, 4, 5])

In [208]:
z[1:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [209]:
z[::5]

array([ 1,  6, 11, 16])

In [210]:
n

array([[  1,   2,   3],
       [  4,   5, 888],
       [  7,   8,   9]])

In [213]:
n[:,1]                                 #2D

array([2, 5, 8])

In [216]:
n[1,:]

array([  4,   5, 888])

In [224]:
n[:1]

array([[1, 2, 3]])

In [221]:
n[0:2, 0:3]

array([[  1,   2,   3],
       [  4,   5, 888]])

In [223]:
n[:, 0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [232]:
e=np.random.randint(20, size=(7,7))
e

array([[ 3,  8,  9, 11, 18, 13, 14],
       [14,  4, 16, 12,  1, 10,  2],
       [ 8,  1, 16, 13, 12, 17, 12],
       [18, 11, 12,  5, 19, 10, 19],
       [ 7, 18,  8, 10, 12, 14,  8],
       [ 0, 14, 17,  5,  4, 15, 13],
       [14, 12,  9,  3,  3,  8,  2]])

In [234]:
subset=e[1:3, 2:5]
subset

array([[16, 12,  1],
       [16, 13, 12]])

In [247]:
subset1=e[:1,4:]
subset1

array([[18, 13, 14]])

In [252]:
subset2=e[1,5]
subset2

10

In [243]:
subset[1,1]=99999

In [244]:
subset

array([[   16,    12,     1],
       [   16, 99999,    12]])

In [248]:
subset1[0,0]=1111111
subset1

array([[1111111,      13,      14]])

In [249]:
e                                                       

array([[      3,       8,       9,      11, 1111111,      13,      14],
       [     14,       4,      16,      12,       1,      10,       2],
       [      8,       1,      16,   99999,      12,      17,      12],
       [     18,      11,      12,       5,      19,      10,      19],
       [      7,      18,       8,      10,      12,      14,       8],
       [      0,      14,      17,       5,       4,      15,      13],
       [     14,      12,       9,       3,       3,       8,       2]])

In [260]:
subset3=e[0:5,0:2].copy()
subset3

array([[ 3,  8],
       [14,  4],
       [ 8,  1],
       [18, 11],
       [ 7, 18]])

In [262]:
subset3[2,1]=8758
subset3

array([[   3,    8],
       [  14,    4],
       [   8, 8758],
       [  18,   11],
       [   7,   18]])

In [263]:
e                                   # There is no 'subset3[2,1]=8758' in the range because of change in the copy range.

array([[      3,       8,       9,      11, 1111111,      13,      14],
       [     14,       4,      16,      12,       1,      10,       2],
       [      8,       1,      16,   99999,      12,      17,      12],
       [     18,      11,      12,       5,      19,      10,      19],
       [      7,      18,       8,      10,      12,      14,       8],
       [      0,      14,      17,       5,       4,      15,      13],
       [     14,      12,       9,       3,       3,       8,       2]])

#### Fancy İndex ####

In [274]:
p=np.arange(10,1,-1)
p

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [275]:
brin=[2,4,5]

In [277]:
p[brin]

array([8, 6, 5])

In [278]:
brin1=[0,2,3,7]

In [279]:
p[brin1]

array([10,  8,  7,  3])

In [283]:
u=np.random.randint(12, size=(4,4))
u                                                     #'Fancy  Index' give us choose high level element.

array([[ 1,  6, 11, 11],
       [10,  7,  2,  5],
       [ 3,  8,  7,  9],
       [ 5,  2, 10,  2]])

In [286]:
row1=np.array([0,2])
column1=np.array([1,3])

In [287]:
u[row1, column1]

array([6, 9])

In [288]:
u

array([[ 1,  6, 11, 11],
       [10,  7,  2,  5],
       [ 3,  8,  7,  9],
       [ 5,  2, 10,  2]])

In [289]:
u[0, [1,2]]                                  #index + fancy index  

array([ 6, 11])

In [292]:
u[:3, [1,2]]                               #slice + fancy index

array([[ 6, 11],
       [ 7,  2],
       [ 8,  7]])

In [293]:
u[:2, [1,2]]

array([[ 6, 11],
       [ 7,  2]])

#### If ####

In [307]:
v=np.arange(0,30,2)
v

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [308]:
v<-1

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [309]:
v>100

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [310]:
v<=15

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False, False, False, False])

In [311]:
v[v<-1]

array([], dtype=int32)

In [312]:
v[v<=15]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [315]:
v[v>=18]

array([18, 20, 22, 24, 26, 28])

In [316]:
v[v==18]

array([18])

In [317]:
v[v!=18]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 20, 22, 24, 26, 28])

#### Mathematical operations ####

In [320]:
v/5

array([0. , 0.4, 0.8, 1.2, 1.6, 2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8,
       5.2, 5.6])

In [321]:
v**2

array([  0,   4,  16,  36,  64, 100, 144, 196, 256, 324, 400, 484, 576,
       676, 784], dtype=int32)

In [322]:
v*2

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56])

In [323]:
v-1

array([-1,  1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27])

In [ ]:
#### ufunc ####
* add ----- Adding(+)
* subtract -----Subtraction(-)
* multiply -----Multiplication(*)
* divide -----Division(/)
* power -----**
* mod --------Mod(%)
* absolute -----Calculate pozitive from negative numbers ()
* log------



In [324]:
v

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [325]:
np.add(v, 5)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

In [348]:
v+5

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

In [326]:
np.subtract(v, 1)

array([-1,  1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27])

In [349]:
v-1

array([-1,  1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27])

In [327]:
np.multiply(v, 2)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56])

In [350]:
v*2

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56])

In [328]:
np.divide(v,2)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

In [351]:
v/2

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

In [329]:
np.power(v, 2)

array([  0,   4,  16,  36,  64, 100, 144, 196, 256, 324, 400, 484, 576,
       676, 784], dtype=int32)

In [352]:
v**2

array([  0,   4,  16,  36,  64, 100, 144, 196, 256, 324, 400, 484, 576,
       676, 784], dtype=int32)

In [330]:
np.power(v, 3)

array([    0,     8,    64,   216,   512,  1000,  1728,  2744,  4096,
        5832,  8000, 10648, 13824, 17576, 21952], dtype=int32)

In [331]:
np.mod(v, 3)

array([0, 2, 1, 0, 2, 1, 0, 2, 1, 0, 2, 1, 0, 2, 1], dtype=int32)

In [353]:
v%3

array([0, 2, 1, 0, 2, 1, 0, 2, 1, 0, 2, 1, 0, 2, 1], dtype=int32)

In [341]:
np.absolute([-1])

array([1])

In [347]:
np.absolute(np.array([-3]))

array([3])

In [355]:
np.sin(360)

0.9589157234143065

In [356]:
np.cos(360)

-0.2836910914865273

In [359]:
ı=np.array([5,55,45,852])

In [360]:
np.log(ı)

array([1.60943791, 4.00733319, 3.80666249, 6.74758653])

In [362]:
np.log10(ı)

array([0.69897   , 1.74036269, 1.65321251, 2.93043959])

In [363]:
u

array([[ 1,  6, 11, 11],
       [10,  7,  2,  5],
       [ 3,  8,  7,  9],
       [ 5,  2, 10,  2]])

In [365]:
np.log10(u)

array([[0.        , 0.77815125, 1.04139269, 1.04139269],
       [1.        , 0.84509804, 0.30103   , 0.69897   ],
       [0.47712125, 0.90308999, 0.84509804, 0.95424251],
       [0.69897   , 0.30103   , 1.        , 0.30103   ]])

In [369]:
np.mean(u)

6.1875

In [371]:
np.mean(u, axis=0)

array([4.75, 5.75, 7.5 , 6.75])

In [372]:
np.mean(u, axis=1)

array([7.25, 6.  , 6.75, 4.75])

In [377]:
np.var(u)

11.27734375

In [378]:
np.std(u)

3.358175658002422

In [380]:
np.corrcoef(u)

array([[ 1.        , -0.93075784,  0.82737924,  0.20751434],
       [-0.93075784,  1.        , -0.64003012, -0.52459298],
       [ 0.82737924, -0.64003012,  1.        , -0.31057366],
       [ 0.20751434, -0.52459298, -0.31057366,  1.        ]])

In [373]:
u.sum()

99

In [374]:
u.min()

1

In [375]:
u.max()

11

* 51*x1+x2=12
* x1+3*x2=100

In [388]:
a=np.array([[51,1],[1,3]])

In [389]:
b=np.array([12,100])

In [390]:
s=np.linalg.solve(a, b)
s

array([-0.42105263, 33.47368421])

* 8*x3+12*x2+x1=52
* 13*x2+2*x1+14*x3=41
* x1+x2+x3=11

In [396]:
l=np.array([[8,12,1],[2,13,1],[1,1,1]])

In [397]:
o=np.array([12,100,11])

In [399]:
k=np.linalg.solve(l, o)
k

array([-13.24657534,   8.52054795,  15.7260274 ])